// Placeholder: the real bindings.rs is generated by cargo-component during the
// wasm32 build. This file satisfies rustfmt / rust-analyzer on native.
// Do NOT edit — cargo-component will overwrite it on a wasm32 build.
